Repository nachimban/nachimban, pull requests merged in 2024-05, with the labels that each got.

#1 chore: 스프링 프로젝트 초기 세팅
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/nachimban/web/WebApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/nachimban/web/WebApplicationTests.java
Labels: BE

#4 chore: 리액트 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE/bug.yml 
  .github/ISSUE_TEMPLATE/deploy.yml 
  .github/ISSUE_TEMPLATE/refactor.yml 
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/__tests__/validation.test.ts
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: FE

#5 Feat: 기초 Entity 설계
  backend/src/main/java/com/nachimban/web/comment/domain/Comment.java
  backend/src/main/java/com/nachimban/web/comment/domain/CommentContent.java
  backend/src/main/java/com/nachimban/web/common/BaseTimeEntity.java
  backend/src/main/java/com/nachimban/web/common/image/ImageUrl.java
  backend/src/main/java/com/nachimban/web/common/util/RegexUtil.java
  backend/src/main/java/com/nachimban/web/member/domain/Email.java
  backend/src/main/java/com/nachimban/web/member/domain/Member.java
  backend/src/main/java/com/nachimban/web/member/domain/Nickname.java
  backend/src/main/java/com/nachimban/web/member/domain/OauthId.java
  backend/src/main/java/com/nachimban/web/oauth/domain/OauthServerType.java
  backend/src/main/java/com/nachimban/web/post/domain/Post.java
  backend/src/main/java/com/nachimban/web/post/domain/PostContent.java
  backend/src/main/java/com/nachimban/web/post/domain/PostImage.java
  backend/src/main/java/com/nachimban/web/post/domain/Title.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/test/java/com/nachimban/web/post/domain/PostCommentContentTest.java
  backend/src/test/java/com/nachimban/web/post/domain/TitleTest.java
Labels: BE, feat

#8 [BE] chore: 서브 모듈 접근 권한 추가
  .github/workflows/be-pull-request.yml
Labels: BE

#9 [BE] feat: 게시판 관련 기능 구현
  backend/src/main/java/com/nachimban/web/auth/presentation/AuthController.java
  backend/src/main/java/com/nachimban/web/auth/support/BearerAuthorizationExtractor.java
  backend/src/main/java/com/nachimban/web/auth/support/JwtTokenProvider.java
  backend/src/main/java/com/nachimban/web/comment/application/CommentService.java
  backend/src/main/java/com/nachimban/web/comment/domain/Comment.java
  backend/src/main/java/com/nachimban/web/comment/domain/CommentRepository.java
  backend/src/main/java/com/nachimban/web/comment/dto/request/CommentCreationRequest.java
  backend/src/main/java/com/nachimban/web/comment/dto/request/CommentUpdateRequest.java
  backend/src/main/java/com/nachimban/web/comment/dto/response/CommentResponse.java
  backend/src/main/java/com/nachimban/web/comment/presentation/CommentController.java
  backend/src/main/java/com/nachimban/web/common/resolver/AuthArgumentResolver.java
  backend/src/main/java/com/nachimban/web/common/security/AuthorizedMember.java
  backend/src/main/java/com/nachimban/web/member/application/MemberService.java
  backend/src/main/java/com/nachimban/web/member/domain/Member.java
  backend/src/main/java/com/nachimban/web/member/domain/MemberRepository.java
  backend/src/main/java/com/nachimban/web/member/dto/request/MemberInfoUpdateRequest.java
  backend/src/main/java/com/nachimban/web/member/dto/response/MemberInfoResponse.java
  backend/src/main/java/com/nachimban/web/member/presentation/MemberController.java
  backend/src/main/java/com/nachimban/web/post/application/PostService.java
  backend/src/main/java/com/nachimban/web/post/domain/Post.java
  backend/src/main/java/com/nachimban/web/post/domain/PostRepository.java
  backend/src/main/java/com/nachimban/web/post/dto/request/PostCreationRequest.java
  backend/src/main/java/com/nachimban/web/post/dto/request/PostUpdateRequest.java
  backend/src/main/java/com/nachimban/web/post/dto/response/PostDetailResponse.java
  backend/src/main/java/com/nachimban/web/post/dto/response/PostResponse.java
  backend/src/main/java/com/nachimban/web/post/presentation/PostController.java
Labels: BE, feat
